version: "4.16.3"
name: market-simulation

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_DB: market
      POSTGRES_USER: root
      POSTGRES_HOST: 0.0.0.0
      POSTGRES_PASSWORD: R2D2-333
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d  # Mount the SQL init directory
  spring-boot-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8091:8091"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/market
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: R2D2-333
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8081:80"
    depends_on:
      - db
  angular-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
volumes:
  postgres-data: